tap "homebrew/bundle"
brew "fd"
brew "fish"
brew "fontconfig"
brew "gh"
brew "git"
brew "lazygit"
brew "lsd"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "rtx"
brew "starship"
brew "zellij"
cask "iterm2"
cask "karabiner-elements"
