tap "homebrew/bundle"
brew "eza"
brew "fd"
brew "fish"
brew "fontconfig"
brew "gh"
brew "git"
brew "mise"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "starship"
brew "stylua"
brew "translate-shell"
brew "zellij"
brew "zoxide"
cask "iterm2"
cask "karabiner-elements"
