palette = "catppuccin_frappe"
command_timeout = 3000

[battery]
disabled = true

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[os]
format = "on [$symbol]($style) "
style = "bold white"
disabled = false

[os.symbols]
Macos = " "

[git_branch]
symbol = " "

[haskell]
symbol = " "

[shell]
fish_indicator = '󰈺 '
style = 'cyan bold'
disabled = false

[directory]
read_only = " 󰌾"
truncation_length = 6
truncation_symbol = '…/'

[nodejs]
symbol = " "

[sudo]
disabled = false
symbol = 'sudo '

[time]
disabled = false

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
